ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# To build a fresh box, from the top dir of this repository:
#
# * vagrant destroy
# * VAGRANT_VAGRANTFILE=box-builder/Vagrantfile vagrant up
# * VAGRANT_VAGRANTFILE=box-builder/Vagrantfile vagrant halt
# * vagrant up --provision
#
# To use more resources:
# ACT_DEVELOPER_CPUS=4 ACT_DEVELOPER_MEMORY=16384 VAGRANT_VAGRANTFILE=box-builder/Vagrantfile vagrant up

Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"
    config.vm.hostname = "act-dev"
    config.vm.network "private_network", ip: "192.168.56.2"

$msg = <<MSG
Run the following commands to finish building your box:
------------------------------------------------------
VAGRANT_VAGRANTFILE=box-builder/Vagrantfile vagrant halt
vagrant up --provision
------------------------------------------------------
MSG

    config.vm.post_up_message = $msg

    # Use ACT_DEVELOPER_* env vars to set vm hardware resources.
    vbox_custom = %w[cpus memory].map do |hw|
        key = "ACT_DEVELOPER_#{hw.upcase}"
        ENV[key] ? ["--#{hw}", ENV[key]] : []
    end.flatten

    config.vm.provider :virtualbox do |vb|
        vb.name = "act-stretch"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        if not vbox_custom.empty?
            vb.customize [ "modifyvm", :id, *vbox_custom ]
        end
    end

    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provision :shell, :path => 'box-builder/provision.sh'
end
